# 按照时间进行水平分表
spring:
  shardingsphere:
    datasource:
      names: m1
      m1:
        type: com.zaxxer.hikari.HikariDataSource
        driver: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/order_db?useUnicode=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    sharding:
      tables:
        t_order:
          actual-data-nodes: m1.t_order_$->{['2021']}_$->{['02', '03','04']} # 数据节点 配置
          #          key-generator:
          #            column: order_id
          #            type: SNOWFLAKE
          table-strategy:
            #            inline:
            #              sharding-column: order_id
            #              algorithm-expression: t_order_$->{order_id % 2 + 1}
            standard:
              sharding-column: create_time
              precise-algorithm-class-name: com.peijun.sharding.config.nokeyid.CreateTimeShardingTableAlgorithm
              range-algorithm-class-name: com.peijun.sharding.config.nokeyid.CreateTimeShardingTableAlgorithm

    props:
      sql:
        show: true
logging:
  level:
    com.peijun: debug
    druid.sql: debug
    org.springframework.web: info
    root: info